### ISSUE TITLE
lib/wire-protocol.js regex issue

### ISSUE THREAD

**Issue by frozon** [davehorton/drachtio-srf#21]
Hi,

I'm facing quite a lot of error `invalid message from server, did not start with length#:`.
I'm using drachtio 4.1.6 package and spotted an issue with a regex in the `_onData` handler of wire-protocol
```js
  _onData(socket, msg) {
    this._logger('<===' + CRLF + msg + CRLF) ;

    if (!this.mapIncomingMsg.has(socket)) {
      this.mapIncomingMsg.set(socket, {
        incomingMsg: '',
        length: -1
      });
    }
    const obj = this.mapIncomingMsg.get(socket) ;
    try {
      while ([...msg].length > 0) {
        let pos ;
        if (0 === obj.incomingMsg.length) {
          //waiting for a new message
          pos = msg.indexOf('#') ;
          if (-1 === pos) {
            if (msg.match(/^\\d+$/)) {
              //it can happen that a message is broken between the length digits and '#'
              obj.incomingMsg = msg ;
              obj.incomingMsgLength = -1 ;  //unknown
              return ;
            }
            else {
              throw new Error('invalid message from server, did not start with length#: ' + msg) ;
            }
          }
          msg = this.parseMessageHeader(msg, pos, obj);
        }
```

The `msg.match(/^\\d+$/)` is probably wrong and should be `msg.match(/^\d+$/)`

Cheers

**Comment by davehorton** [comment]
can you show some drachtio log snippets showing the kinds of errors you are seeing?

Also, please update to using drachtio-srf, and remove the drachtio dependency from your app, when you have a chance

**Comment by frozon** [comment]
Hi! Here are some logs showing the above error.

```
/usr/src/app/node_modules/drachtio/lib/wire-protocol.js:280
        throw err;
        ^

Error: invalid message from server, did not start with length#: 8ff6b23f-4d5c-44be-ba7f-40d297fd49c2|sip|network|345|udp|123.44.33.77|5060|04:39:14.328815|ca580637-215f-4e60-8cff-0e0cc621536c||
SIP/2.0 200 OK
Via: SIP/2.0/UDP 99.178.99.80;rport=5060;branch=z9hG4bKgZ9Z662pXDZyB;received=1.2.3.79
From: <sip:99.178.99.80:5060>;tag=X5m0UeeSaSarS
To: <sip:123.44.33.77>;tag=120fbc1eeeae6ef0cbbeec6e3f8738a6.94ee
Call-ID: 47f033b7-46e9-1237-78a1-0242ac110011
CSeq: 129237113 OPTIONS
Server: Kamailio Edge 5.1
Content-Length: 0


    at WireProtocol._onData (/usr/src/app/node_modules/drachtio/lib/wire-protocol.js:244:21)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:257:13)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```

**Comment by frozon** [comment]
Just sent you a mail with a PCAP
I'm runing drachtio v0.7.3 and drachtio-srf only latest version too 4.3.7

**Comment by davehorton** [comment]
thx - sorry for the delay in responding, I've been on holiday.  Returning this weekend and will check into this soonest.

**Comment by davehorton** [comment]
The pcap you sent seems to be filtered to only show sip traffic.....actually, I wanted to see all the traffic on the server, specifically the tcp traffic between the server and the drachtio-srf application.  Can you send me the full (unfiltered) trace?

**Comment by frozon** [comment]
Hi, I've only sniffed SIP traffic inside the drachtio server container.
Will make another PCAP asap without SIP filter and get it to you.

**Comment by davehorton** [comment]
Actually, if you can get at the PCAP From the server on which the application is running that is what I would like to see. It is the incoming message from the server to the application, not the sip message which is causing the problem

**Comment by davehorton** [comment]
also, I want to make sure I understand your test setup.  From looking at your 'probing' code above, it seems like you have one drachtio server+app sending OPTIONS to a second drachtio server (presumably with its own app attached), is that correct?

If possible, I would like to help you update your code to remove the dependency on the 'drachtio' npmjs module as now you should only need to import 'drachtio-srf'.  If you would like, perhaps you can make a private project and grant me access so I can either indicate the changes required or make them on a new branch or PR

**Comment by frozon** [comment]
The setup is the following one
- an anycasted drachtio in a container
- a container with drachtio-srf (I already removed dependency to drachtio a while ago as you pointed out in the first message to use drachtio-srf instead)
- plenty kamailio backend

The js app attached to the frontend drachtio have a full list of Kamailio backend which are probbed every 10s to check if they are alive or not and their respective latency.

So in the current setup there is only 1 drachtio container and only 1 drachtio app (if I can named it like this)

Then on REGISTER and/or INVITE the drachtio app proxy the request to the kamailio which has the less latency. Hope that helps to understand our setup.

**Comment by davehorton** [comment]
It sounds like the front-end drachtio-srf app is quite simple.  Could you also just send me a zipfile of that project (inlcuding package.json, etc)?

But the pcap would be quite useful as well..

**Comment by frozon** [comment]
Sorry it took me a while to be able to get this as I was busy on something else.
I'm going to mail you the dump file and the error I grabbed couple minutes ago.

**Comment by davehorton** [comment]
ok let me know your results from the latest version.

For some reason, in that pcap I see only the traffic to the sip port....there should have been tcp traffic leaving the container from tcp port 9022 going to the drachtio-srf app, but I can't find it in the trace for some reason..

**Comment by davehorton** [comment]
actually, I see that traffic now -- it was coming from tcp port 8022.  Studying it now, meanwhile when you have had the chance to test for a while with the new code let me know your results

**Comment by frozon** [comment]
The app have been running for 20hours now without any crash. Your fix did the trick, thanks a lot 😄 
Let me know if you need more material regarding to the underlying issue I'll try my best to provide it
