### ISSUE TITLE
No response after ACK to 407 Proxy Authentication challenge

### ISSUE THREAD

**Issue by byoungdale** [davehorton/drachtio-srf#3]
I cannot get drachtio to resend another INVITE after receiving a 407 Proxy Authentication challenge.

First I tried with drachtio-srf, but it only sends an ACK and nothing else happens:

```javascript
srf.createUacDialog(`sip:${opts.callednumber}@${opts.domain}`, {
    localSdp: sdp,
    callerNumber: opts.user,
    calledNumber: opts.calledNumber,
    headers: {
      'From': `sip:${opts.user}@${opts.domain}`,
      'User-Agent': 'test UA',
      'Contact': `sip:${opts.user}@${opts.domain}:${opts.hostport}`
    },
    auth: {
      username: opts.user,
      password: opts.password
    }
  }, function(err, dialog) {
    if( err ) { return err }
    debug('created uac dialog: ', dialog);
  });
```

When I tried using drachtio, the same SIP signaling occurred, but I did get an error:

Here is the code:
``` javascript
  srf.request({
    uri: `sip:${opts.callednumber}@${opts.domain}`,
    method: 'INVITE',
    headers: {
      'From': `sip:${opts.user}@${opts.domain}`,
      'User-Agent': 'test UA',
      'Contact': `sip:${opts.user}@${opts.domain}:${opts.hostport}`,
    },
    auth: {
      username: opts.user,
      password: opts.password
    }
  }, function (err, req ){
    if( err ) console.error( err );

    req.on('response', function(response) {
      console.log('we got a response');
    });
  });
```

I got the following error:
```
drachtioDialer/node_modules/drachtio/lib/client/digest-client.js:139
  var challenge = digest.substr(digest.indexOf(prefix) + prefix.length);
                        ^

TypeError: Cannot read property 'substr' of undefined
    at parseChallenge (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/digest-client.js:139:25)
    at /Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/digest-client.js:42:21
    at fn (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/digest-client.js:30:50)
    at DigestClient.authenticate (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/digest-client.js:37:3)
    at handle (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:186:14)
    at Socket.onData (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:345:4)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
```

So, in digest-client.js, I replaced:
```javascript
var challenge = parseChallenge(self.res.get('www-authenticate'));
```
with
```javascript
    // adding this to get proxy-authenticate challenges as well
    if (self.res.get('www-authenticate') === undefined) {
      var challenge = parseChallenge(self.res.get('proxy-authenticate'));
    } else {
      var challenge = parseChallenge(self.res.get('www-authenticate'));
    }
```

Then I got the following error:
```
drachtioDialer/node_modules/drachtio/lib/client/agent.js:189
								req.on('response', l) ;
								   ^

TypeError: Cannot read property 'on' of undefined
    at /Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:190:12
    at Array.forEach (native)
    at Object.callback (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:189:38)
    at agent.pendingRequests.(anonymous function) (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:436:11)
    at handle (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:219:4)
    at Socket.onData (/Users/byoungdale/Documents/drachtio/drachtioDialer/node_modules/drachtio/lib/client/agent.js:345:4)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
```

When I did a debug on ```onData``` function, I get:

```onData: msg:  105#50a4acdd-caf5-4b44-9fb1-29f6f7fc93c8|response|3bd34460-04e6-11e7-9ef2-733c78e8dad2|NOK|Error creating leg```

From the drachtio-server:
```
SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/UDP 10.0.1.183;received=192.168.64.22;branch=z9hG4bKrrKXUgDHHXQDj
To: <sip:5555555555@example.com>;tag=sansay232705rdb53
From: <sip:username@example.com>;tag=5j2D1meNKt4Nr
Call-ID: 133ceeb9-7f89-1235-71b3-0800271b9bde
CSeq: 104202563 INVITE
Proxy-Authenticate: Digest realm="example.com", nonce="f6ff5487-dda0-4d25-a793-188e91034f2f", algorithm=MD5, qo
p="auth"
User-Agent: SIP Server
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Content-Length: 0

00014a09|2017-Mar-09 16:34:15.208809| tport.c:3023 tport_deliver() tport_deliver(0xfb6aa0): msg 0xfe3960 (801 bytes) from udp/192.168.1.9:5060 next=(nil)
00014a0a|2017-Mar-09 16:34:15.208833| nta.c:3299 agent_recv_response() nta: received 407 Proxy Authentication Required for INVITE (104202563)
00014a0b|2017-Mar-09 16:34:15.208856| nta.c:3366 agent_recv_response() nta: 407 Proxy Authentication Required is going to a transaction
00014a0c|2017-Mar-09 16:34:15.208876| tport.c:4222 tport_release() tport_release(0xfb6aa0): 0xfc7e90 by 0xfdfcb0 with 0xfe3960
00014a0d|2017-Mar-09 16:34:15.208933| tport.c:3257 tport_tsend() tport_tsend(0xfb6aa0) tpn = UDP/192.168.1.9:5060
00014a0e|2017-Mar-09 16:34:15.208966| tport.c:4046 tport_resolve() tport_resolve addrinfo = 192.168.1.9:5060
00014a0f|2017-Mar-09 16:34:15.208988| tport.c:4680 tport_by_addrinfo() tport_by_addrinfo(0xfb6aa0): not found by name UDP/192.168.1.9:5060
00014a10|2017-Mar-09 16:34:15.209165| tport.c:3492 tport_send_msg() tport_vsend returned 325
00014a11|2017-Mar-09 16:34:15.209236| send 325 bytes to udp/[192.168.1.9]:5060 at 16:34:15.209034:
ACK sip:5555555555@example.com SIP/2.0
Via: SIP/2.0/UDP 10.0.1.183;branch=z9hG4bKrrKXUgDHHXQDj
Max-Forwards: 70
From: <sip:username@example.com>;tag=5j2D1meNKt4Nr
To: <sip:5555555555@example.com>;tag=sansay232705rdb53
Call-ID: 133ceeb9-7f89-1235-71b3-0800271b9bde
CSeq: 104202563 ACK
Content-Length: 0

00014a12|2017-Mar-09 16:34:15.209268| nta.c:8304 outgoing_send() nta: sent ACK (104202563) to UDP/192.168.1.9:5060
00014a13|2017-Mar-09 16:34:15.209290| nta.c:8722 outgoing_free() nta: outgoing_free(0xfe3e80)
00014a14|2017-Mar-09 16:34:15.209346| ClientController::removeDialog - dialog not found: 1dc5801e-595a-469a-9858-0a586922de71
00014a15|2017-Mar-09 16:34:15.209375| nta.c:4470 nta_leg_destroy() nta_leg_destroy(0xfd5ab0)
00014a16|2017-Mar-09 16:34:15.216729| nta.c:4423 nta_leg_tcreate() nta_leg_tcreate(): Missing local dialog address
00014a17|2017-Mar-09 16:34:15.216794| SipDialogController::doSendRequestOutsideDialog - Error creating leg
```

**Comment by davehorton** [comment]
can you retry your test, and remove 'Contact' from the headers you are supplying?  The drachtio server will automatically insert a proper header, and I want to see if that is contributing to the problem, as my test case is working.  

So change this:

```
headers: {
      'From': `sip:${opts.user}@${opts.domain}`,
      'User-Agent': 'test UA',
      'Contact': `sip:${opts.user}@${opts.domain}:${opts.hostport}`
    },
```
to this:
```
headers: {
      'From': `sip:${opts.user}@${opts.domain}`,
      'User-Agent': 'test UA'
    },
```

BTW, you can also remove the 'From' header if you want -- by supplying 'callingNumber' the drachtio server will construct an appropriate From header

**Comment by byoungdale** [comment]
Still got this error on the console:
```
172#8d3680a9-2360-4ba9-a03f-d785698824ce|response|66f6dc50-05a0-11e7-88c2-6bfa00dfdeb3|NOK|Server error: ACK for non-success final response is automatically generated by server
```
And this error on the server:
```
ClientController::removeDialog - dialog not found: a26105e3-9e56-4e05-a301-4b4df102654d
```

Here is my createUacDialog section:
```javascript
srf.createUacDialog(`sip:${opts.callednumber}@${opts.domain}`, {
    localSdp: sdp,
    callerNumber: opts.user,
    calledNumber: opts.calledNumber,
    headers: {
      'From': `sip:${opts.user}@${opts.domain}`,
      'User-Agent': 'test UA'
    },
    auth: {
      username: opts.user,
      password: opts.password
    }
  }, function(err, dialog) {
    if( err ) { return err }
    debug('created uac dialog: ', dialog);
  });
```

**Comment by davehorton** [comment]
ok I will try to recreate that test app.

Neither of those messages are actually concerning -- the first just indicates that although the client app told the server to generate an ACK, the server had already done so.  In all cases other than a 200 OK the server generates the ACK automatically.  In the case of a 200 OK, to allow for a delayed negotation where the client is providing an SDP in the ACK, the server can not generate the ACK so it waits for the client to do so.  It looks like the client is generating the ACK in all cases (event non 200 OK), which is fine the server just discards the request (but does generate this error).

The other message is also related to the fact that the server has already disposed of the transaction since it failed.

I'll update once I put my test app together.....Also, you are testing against the latest 'develop' branch correct?

**Comment by byoungdale** [comment]
I am using 3.0.1 from the NPM package. Is that the latest?

**Comment by davehorton** [comment]
Yes, sorry I mean the version of drachtio-server

**Comment by byoungdale** [comment]
Oh yes, I downloaded it straight from the respository. Here is what I get on the server:

```
drachtioserver:~$ drachtio --version
0.4.1-rc3-34-g0b59693
```

**Comment by davehorton** [comment]
There have been some updates recently, and they may not fix things but it would be good to be on the latest.  I would do a git pull and rebuild (or better yet, blow away your current install and rebuild according to the instructions [here](https://github.com/davehorton/drachtio-server/blob/develop/README.md)

 drachtio --version
0.5.0-rc5

**Comment by byoungdale** [comment]
Upgraded to 0.5.0-rc5, but with the same results.

**Comment by byoungdale** [comment]
When I tried the code below, drachtio did respond to the 407 with an INVITE with credentials:

```javascript
  srf.request({
    uri: `sip:${opts.callednumber}@${opts.domain}`,
    method: 'INVITE',
    body: sdp,
    headers: {
      'From': `sip:${opts.user}@${opts.domain}`,
      'User-Agent': 'test UA'
    },
    auth: {
      username: opts.user,
      password: opts.password
    }
  }, function (err, req ){
    if( err ) console.error( err );

    req.on('response', function(response) {
      console.log('we got a response');
    });
  });
```

I did have to change line 42 of ```digest-client.js``` from:
```javascript
var challenge = parseChallenge(self.res.get('www-authenticate'));
```
to
```javascript
if (self.res.get('www-authenticate') === undefined) {
  var challenge = parseChallenge(self.res.get('proxy-authenticate'));
} else {
  var challenge = parseChallenge(self.res.get('www-authenticate'));
}
```

**Comment by davehorton** [comment]
can you update to the latest drachtio-srf with your original app and retry?  I've pushed a fix

**Comment by davehorton** [comment]
I've checked in a fix and a test case, can you verify your app works with the latest?

**Comment by byoungdale** [comment]
Worked! Responded with credentials in the INVITE to the 407. Thank you!
