### ISSUE TITLE
Example request code not working

### ISSUE THREAD

**Issue by amoonrah** [davehorton/drachtio-srf#49]
Hi there,

I just came across your software and it's really something I would like to use in our testing environment.

I'm just trying something simple and it's not working, I'm new to node.js and I have not done JS in a while, so please I apologize if this is not the right forum to ask this.

I'm just running your example to send an option request out, and I get an error when I run the script. can you just tell me if it's a problem with the example code ..

const Srf = require('drachtio-srf');
const srf = new Srf();
const assert = require('assert');

srf.connect({
  host: '172.17.0.2',
  port: 9022,
  secret: 'cymru'
});

srf
  .on('connect', (err, hostport) => {
    console.log(`connected to a drachtio server listening on: ${hostport}`);
  })
  .on('error', (err) => {
    console.log(`Error connecting to drachtio server: ${err}`);
    process.exit(1);
  });

srf.request('sip:1234@example.com', {
  method: 'OPTIONS'
}, (err, req) => {
  // req is the SIP request that went out over the wire
  req.on('response', (res) => {
    console.log(`received ${res.status} response to our OPTIONS request`);
  });
});

output

[root@SIPp1 geo-test]# node app.js
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(typeSocket(socket))

    at sockPort (/root/dev/geo-test/node_modules/drachtio-srf/lib/drachtio-agent.js:25:3)
    at DrachtioAgent._getDefaultSocket (/root/dev/geo-test/node_modules/drachtio-srf/lib/drachtio-agent.js:505:56)
    at DrachtioAgent._normalizeParams (/root/dev/geo-test/node_modules/drachtio-srf/lib/drachtio-agent.js:254:21)
    at DrachtioAgent.request (/root/dev/geo-test/node_modules/drachtio-srf/lib/drachtio-agent.js:328:25)
    at Function.proto.(anonymous function) [as request] (/root/dev/geo-test/node_modules/delegates/index.js:40:31)
    at __x (/root/dev/geo-test/node_modules/drachtio-srf/lib/srf.js:923:19)
    at Srf.request (/root/dev/geo-test/node_modules/drachtio-srf/lib/srf.js:927:7)
    at Object.<anonymous> (/root/dev/geo-test/app.js:22:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[root@SIPp1 geo-test]# s

**Comment by davehorton** [comment]
wait until you get the 'connect' event before you try to send your request

**Comment by amoonrah** [comment]
That worked ... guess I have a lot to learn about programing with nodejs

Thank you for the quick response.

**Comment by davehorton** [comment]
Excellent!  Don't worry, you will love node.js
