### ISSUE TITLE
How to originate call from drachtio

### ISSUE THREAD

**Issue by enp** [davehorton/drachtio-srf#74]
Tried to originate call from drachtio with:

```
const Srf = require('drachtio-srf')
const srf = new Srf()

srf.connect({ host: '127.0.0.1', port: 9022, secret: 'drachtio' })

srf.on('connect', async (err, endpoint) => {
  console.log(`Connected to a drachtio server listening on: ${endpoint}`)
  try {
    const dialog = await srf.createUac('sip:101@10.0.0.1')
    dialog.on('destroy', () => console.log('called party ended call'))
  } catch (err) {
    console.log(err)
  }
})
```

Error was:

```
Connected to a drachtio server listening on: udp/10.0.0.2:5060
TypeError: srf.createUac is not a function
    at Srf.<anonymous> (/home/app/drachtio/call.js:11:30)
    at Srf.emit (events.js:223:5)
    at Immediate._onImmediate (/home/app/drachtio/node_modules/drachtio-srf/lib/srf.js:76:64)
    at processImmediate (internal/timers.js:439:21)
```

What is wrong with my code? Why already initialized srf instance has no createUac function?

**Comment by davehorton** [comment]
Use [`Srf#createUAC`](https://drachtio.org/api#srf-create-uac) (not createUac)

**Comment by enp** [comment]
Thank you! Fix https://www.drachtio.org/docs#sip-messages please, I see srf.createUac in all code examples :)

**Comment by enp** [comment]
New error after replacing srf.createUac by srf.createUAC:

```
TypeError: Cannot set property 'uri' of undefined
    at Srf.createUAC (/home/app/drachtio/node_modules/drachtio-srf/lib/srf.js:346:16)
    at Srf.<anonymous> (/home/app/drachtio/call.js:11:30)
    at Srf.emit (events.js:223:5)
    at Immediate._onImmediate (/home/app/drachtio/node_modules/drachtio-srf/lib/srf.js:76:64)
    at processImmediate (internal/timers.js:439:21)
```

First argument of srf.createUAC (uri) is set, so why drachtio can't set property 'uri' of some (what?) undefined?

**Comment by enp** [comment]
callingNumber/calledNumber or From/To headers looks requires and fixes my issue
