### ISSUE TITLE
CDR event listeners giving error if configured before connect

### ISSUE THREAD

**Issue by alexandremiguelabreu** [davehorton/drachtio-srf#79]
This code works:
```javascript
const Srf = require("drachtio-srf");
const srf = new Srf();
const config = require("config");

srf.on("connect", (err, hostport) => {
  console.log(`connected to a drachtio server listening on: ${hostport}`);
});
srf.on("error", (err) => {
  console.log(`Error connecting to drachtio server: ${err}`);
});

srf.connect(config.get("drachtio"));

srf.on("cdr:attempt", (source, time, msg) => {
  console.log(
    `got attempt record from ${source} at ${time}: msg.get('Call-Id')`
  );
});
```

But if the `cdr:attempt`listener is set before the connect, the app fails to start:
```javascript
const Srf = require("drachtio-srf");
const srf = new Srf();
const config = require("config");

srf.on("connect", (err, hostport) => {
  console.log(`connected to a drachtio server listening on: ${hostport}`);
});
srf.on("error", (err) => {
  console.log(`Error connecting to drachtio server: ${err}`);
});

srf.on("cdr:attempt", (source, time, msg) => {
  console.log(
    `got attempt record from ${source} at ${time}: msg.get('Call-Id')`
  );
});

srf.connect(config.get("drachtio"));
```

Output error:
```
/Users/alex/drachtio-tests/node_modules/drachtio-srf/lib/proto.js:26
    app.on(event);
        ^

TypeError: app.on is not a function
    at _cachedEvents.forEach (/Users/alex/drachtio-tests/node_modules/drachtio-srf/lib/proto.js:26:9)
    at Array.forEach (<anonymous>)
    at Function.app._init (/Users/alex/drachtio-tests/node_modules/drachtio-srf/lib/proto.js:25:22)
    at Function.app.connect (/Users/alex/drachtio-tests/node_modules/drachtio-srf/lib/proto.js:43:37)
    at Srf.connect (/Users/alex/drachtio-tests/node_modules/drachtio-srf/lib/srf.js:107:21)
    at Object.<anonymous> (/Users/alex/drachtio-tests/test.js:18:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

Since there is no problem setting the others listeners (i.e. `srf.on("connect", ...)` and `srf.on("error", ...)`) before the connecting to Drachtio server, I believe that with the CDR events that must be also possible.

If this is a bug in your opinion, I can try to fix it or, at least, try to output a more comprehensive error message.

**Comment by davehorton** [comment]
I agree its a bug.  Would be great if you have a fix and want to give me a PR !

**Comment by alexandremiguelabreu** [comment]
Hi @davehorton, I have retested the above scenarios with the changes that @joelact have committed.

I have tested:

> REGISTER
< 401 Unauthorized
> REGISTER
< 200 OK

> INVITE
< 100 Trying
< 200 OK
> ACK
> BYE
< 200 OK

**Scenario A** - CDR listeners declared before the connect:
```
INVITE TO 123
CDR:ATTEMPT :: network :: 20:58:58.469727 :: w8pMMwE3PuVEi.nZ8sNnmA1szTwnbWf5
CDR:ATTEMPT :: application :: 20:58:58.504828 :: 5eeac779-2c49-1239-f7bc-0050568e3b78
CDR:START :: network :: 20:58:58.519951 :: 5eeac779-2c49-1239-f7bc-0050568e3b78
CDR:START :: application :: 20:58:58.540494 :: w8pMMwE3PuVEi.nZ8sNnmA1szTwnbWf5
CDR:STOP :: network :: 20:59:16.874209 :: w8pMMwE3PuVEi.nZ8sNnmA1szTwnbWf5
CDR:STOP :: application :: 20:59:16.882657 :: 5eeac779-2c49-1239-f7bc-0050568e3b78
```

**Scenario B** - CDR listeners declared after the connect:
```
INVITE TO 123
CDR:ATTEMPT :: network :: 20:59:46.018049 :: P7MQKpj84CW-5rP2uInR6t5TmD2Zxs6U
CDR:ATTEMPT :: application :: 20:59:46.049589 :: 7b41907e-2c49-1239-f7bc-0050568e3b78
CDR:START :: network :: 20:59:46.061799 :: 7b41907e-2c49-1239-f7bc-0050568e3b78
CDR:START :: application :: 20:59:46.085633 :: P7MQKpj84CW-5rP2uInR6t5TmD2Zxs6U
CDR:STOP :: network :: 20:59:48.983342 :: P7MQKpj84CW-5rP2uInR6t5TmD2Zxs6U
CDR:STOP :: application :: 20:59:48.992869 :: 7b41907e-2c49-1239-f7bc-0050568e3b78
```

All the listeners are working fine. I will close this issue.

When can we expect this change will be available in NPM?

**Comment by davehorton** [comment]
just pushed as 4.4.35
